version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "3500:3500"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3500
    networks:
      - app-network

networks:
  app-network:
    driver: bridge