name: Push Frontend Image to ACR

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: mseke.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Build and push frontend image
        run: |
          docker build \
            --build-arg REACT_APP_API_BASE_URL=https://msekebackend-gebgewggdaakancz.canadaeast-01.azurewebsites.net \
            -t mseke.azurecr.io/frontend-app:latest ./frontend
          docker push mseke.azurecr.io/frontend-app:latest
